name: CocaineGrindingPlugin
version: 1.0
main: com.example.cocainegrinding.CocaineGrindingPlugin
api-version: 1.12
commands:
  setcocainelocation:
    description: Stel een locatie in voor cocaïneplanten.
  listcocainelocations:
    description: Toon een lijst van alle ingestelde cocaïneplantlocaties.
permissions: {}
